import os
from dotenv import load_dotenv

# ENVs

load_dotenv()

ADAFRUIT_IO_USERNAME = os.getenv("ADAFRUIT_IO_USERNAME")
ADAFRUIT_IO_KEY = os.getenv("ADAFRUIT_IO_KEY")
SMTP_RECIPIENT = os.getenv("SMTP_RECIPIENT")
SMTP_CC = os.getenv("SMTP_CC")
SMTP_FROM = os.getenv("SMTP_FROM")
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = os.getenv("SMTP_PORT")

# Global Variables

TEMP_THRESHOLD_HIGH = 25.0
TEMP_THRESHOLD_LOW = 19.0
READ_INTERVAL_SECONDS = 30
LOG_INTERVAL_SECONDS = 300
TEMP_HYSTERESIS = 1.0